# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    custom_components.plant_monitor_plus: debug

debugpy:
  start: true
  wait: false
  port: 5678

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
